import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface ReceiptData {
  schoolName: string;
  schoolAddress?: string;
  schoolPhone?: string;
  receiptNo: string;
  paymentNo: string;
  studentName: string;
  admissionNo: string;
  grade: string;
  amount: number;
  method: string;
  mpesaReceipt?: string;
  reference?: string;
  notes?: string;
  date: string;
  receivedBy?: string;
  term?: string;
  academicYear?: number;
  voteHeads?: { name: string; amount: number }[];
}

export function generateReceipt(data: ReceiptData): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFillColor(201, 100, 66); // terracotta
  doc.rect(0, 0, pageWidth, 40, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text(data.schoolName, pageWidth / 2, 18, { align: "center" });

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  if (data.schoolAddress) {
    doc.text(data.schoolAddress, pageWidth / 2, 26, { align: "center" });
  }
  if (data.schoolPhone) {
    doc.text(`Tel: ${data.schoolPhone}`, pageWidth / 2, 33, { align: "center" });
  }

  // Receipt title
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("PAYMENT RECEIPT", pageWidth / 2, 55, { align: "center" });

  // Receipt info
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const leftCol = 15;
  const rightCol = pageWidth / 2 + 10;
  let y = 68;

  const addField = (label: string, value: string, x: number, yPos: number) => {
    doc.setFont("helvetica", "bold");
    doc.text(label, x, yPos);
    doc.setFont("helvetica", "normal");
    doc.text(value, x + 35, yPos);
  };

  addField("Receipt No:", data.receiptNo, leftCol, y);
  addField("Date:", new Date(data.date).toLocaleDateString("en-KE", { year: "numeric", month: "long", day: "numeric" }), rightCol, y);
  y += 8;

  addField("Payment No:", data.paymentNo, leftCol, y);
  addField("Method:", data.method.toUpperCase(), rightCol, y);
  y += 8;

  if (data.mpesaReceipt) {
    addField("M-Pesa Ref:", data.mpesaReceipt, leftCol, y);
    y += 8;
  }

  if (data.reference) {
    addField("Reference:", data.reference, leftCol, y);
    y += 8;
  }

  // Student info
  doc.setDrawColor(200, 200, 200);
  doc.line(leftCol, y, pageWidth - leftCol, y);
  y += 8;

  addField("Student:", data.studentName, leftCol, y);
  addField("Grade:", data.grade, rightCol, y);
  y += 8;

  addField("Admission No:", data.admissionNo, leftCol, y);
  if (data.term && data.academicYear) {
    addField("Term:", `Term ${data.term} ${data.academicYear}`, rightCol, y);
  }
  y += 10;

  // Amount
  doc.setFillColor(245, 245, 243);
  doc.roundedRect(leftCol, y - 5, pageWidth - 2 * leftCol, 20, 3, 3, "F");

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("AMOUNT PAID", leftCol + 10, y + 3);
  doc.setFontSize(16);
  doc.setTextColor(201, 100, 66);
  doc.text(`KES ${data.amount.toLocaleString()}`, pageWidth - leftCol - 10, y + 5, { align: "right" });
  doc.setTextColor(0, 0, 0);
  y += 25;

  // Vote heads breakdown
  if (data.voteHeads && data.voteHeads.length > 0) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("Fee Breakdown", leftCol, y);
    y += 5;

    autoTable(doc, {
      startY: y,
      head: [["Vote Head", "Amount (KES)"]],
      body: data.voteHeads.map((vh) => [vh.name, vh.amount.toLocaleString()]),
      theme: "grid",
      headStyles: { fillColor: [201, 100, 66], fontSize: 9 },
      bodyStyles: { fontSize: 9 },
      margin: { left: leftCol, right: leftCol },
    });

    y = (doc as any).lastAutoTable.finalY + 10;
  }

  // Notes
  if (data.notes) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "italic");
    doc.text(`Note: ${data.notes}`, leftCol, y);
    y += 8;
  }

  // Footer
  doc.setDrawColor(200, 200, 200);
  doc.line(leftCol, y, pageWidth - leftCol, y);
  y += 8;

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(128, 128, 128);
  doc.text("This is a computer-generated receipt.", pageWidth / 2, y, { align: "center" });
  y += 5;
  doc.text(`Generated by Edufy Finance on ${new Date().toLocaleDateString("en-KE")}`, pageWidth / 2, y, { align: "center" });

  if (data.receivedBy) {
    y += 10;
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.text(`Received by: ${data.receivedBy}`, leftCol, y);
    y += 15;
    doc.line(leftCol, y, leftCol + 60, y);
    doc.setFontSize(8);
    doc.text("Authorized Signature", leftCol, y + 4);
  }

  // Save
  doc.save(`receipt-${data.receiptNo}.pdf`);
}

export function generateReportPdf(
  title: string,
  headers: string[],
  rows: (string | number)[][],
  filename: string,
  summary?: { label: string; value: string }[]
): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFillColor(201, 100, 66);
  doc.rect(0, 0, pageWidth, 30, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(title, pageWidth / 2, 18, { align: "center" });

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated: ${new Date().toLocaleDateString("en-KE")}`, pageWidth / 2, 25, { align: "center" });

  let y = 40;

  // Summary
  if (summary && summary.length > 0) {
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    summary.forEach((s) => {
      doc.setFont("helvetica", "bold");
      doc.text(`${s.label}:`, 15, y);
      doc.setFont("helvetica", "normal");
      doc.text(s.value, 60, y);
      y += 7;
    });
    y += 5;
  }

  // Table
  autoTable(doc, {
    startY: y,
    head: [headers],
    body: rows.map((r) => r.map(String)),
    theme: "grid",
    headStyles: { fillColor: [201, 100, 66], fontSize: 9 },
    bodyStyles: { fontSize: 8 },
    margin: { left: 15, right: 15 },
  });

  // Footer
  const finalY = (doc as any).lastAutoTable.finalY + 10;
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text("Generated by Edufy Finance", pageWidth / 2, finalY, { align: "center" });

  doc.save(filename);
}
